export type {
  ScentIdentity,
  ScentSnapshot,
  ScentDrift,
  ScentRisk,
  ScentObservation,
  ScentInitOptions,
  RiskFlag,
  SignalMap,
  ConfidenceBand,
  RiskBand,
  DriftClassification,
  IdentityContinuity,
  PersistencePolicy,
} from './types.js';
